### ISSUE TITLE
cloud.sylabs.io slurm containers not found

### ISSUE THREAD

**Issue by bordesf** [sylabs/wlm-operator#201]
Since today, I can't access anymore to https://cloud.sylabs.io/library/slurm/operator nor https://cloud.sylabs.io/library/slurm/configurator:latest. This leads to error when trying to deploy the wlm-operator.

**Comment by dctrud** [comment]
@bordesf - in the web URLs there is an extra `/library`... so...

https://cloud.sylabs.io/library/library/slurm/operator
https://cloud.sylabs.io/library/library/slurm/configurator:latest

... will work and correspond to a `singularity pull` of...

library://library/slurm/operator
library://library/slurm/configurator:latest

We understand this is a bit confusing. The first `/library` in the cloud.sylabs.io takes you to the `library` service there, and then the second `/library` is part of the container reference.

**Comment by bordesf** [comment]
Thanks for the explanation :)
